version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
      - "9002:9000"
      # I use 8002 and 9002 to avoid conflict with other local services
    environment:
      - DATABASE_URL=postgresql+asyncpg://evuser:evpass@db:5432/evcs
      - POSTGRES_DB=evcs
      - POSTGRES_USER=evuser
      - POSTGRES_PASSWORD=evpass
      
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=evcs
      - POSTGRES_USER=evuser
      - POSTGRES_PASSWORD=evpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evuser -d evcs"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge